API: OpenSim::OffsetFrame< C > Class Template Reference
OpenSim::OffsetFrame< C > Class Template Reference abstract
An OffsetFrame is a Frame whose transform (translation and orientation) with respect to another (parent) Frame is constant in time.
OpenSim Properties, Sockets, Outputs, Inputs
Properties (single-value)
SimTK::Vec3 translation
"Translational offset (in meters) of this frame's origin from the parent " "frame's origin, expressed in the parent frame."
SimTK::Vec3 orientation
"Orientation offset (in radians) of this frame in its parent frame, " "expressed as a frame-fixed x-y-z rotation sequence."
Sockets
C parent
"The parent frame to this frame."
Public Member Functions
OffsetFrame ()
By default, the frame is not connected to any parent frame, and its transform is an identity transform.
OffsetFrame (const C &parent, const SimTK::Transform &offset)
A convenience constructor that initializes the parent connection and offset Transform in the parent frame.
OffsetFrame (const std::string &name, const C &parent, const SimTK::Transform &offset)
A convenience constructor that initializes the parent connection by name and of the offset Transform in the parent frame.
OffsetFrame (const std::string &name, const std::string &parentName, const SimTK::Transform &offset)
A convenience constructor that initializes the parent connection by name and of the offset Transform in the parent frame.
void setParentFrame (const C &parent)
Sets the parent reference frame.
const C & getParentFrame () const
Get the parent reference frame.
const SimTK::Transform & getOffsetTransform () const
Get the transform that describes the translational and rotational offset of this frame (F frame) relative to its parent frame (B frame).
void setOffsetTransform (const SimTK::Transform &offset)
Sets the transform the translates and rotates this frame (F frame) from its parent frame (P frame).
void extendScale (const SimTK::State &s, const ScaleSet &scaleSet) override
Scale the offset given scale factors for spatial (XYZ) dimensions.
Property-related functions
const SimTK::Vec3 & get_translation () const
Get the value of the translation property.
SimTK::Vec3 & upd_translation ()
Get a writable reference to the translation property.
void set_translation (const SimTK::Vec3 &value)
Set the value of the translation property.
const SimTK::Vec3 & get_orientation () const
Get the value of the orientation property.
SimTK::Vec3 & upd_orientation ()
Get a writable reference to the orientation property.
void set_orientation (const SimTK::Vec3 &value)
Set the value of the orientation property.
Socket-related functions
void connectSocket_parent (const Object &object)
Connect the 'parent' Socket to an object of type C.
Auto-generated functions
static OffsetFrame * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "OffsetFrame_<T>_".
OffsetFrame * clone () const override=0
const std::string & getConcreteClassName () const override=0
Detailed Description
template<class C = Frame>
class OpenSim::OffsetFrame< C >
An OffsetFrame is a Frame whose transform (translation and orientation) with respect to another (parent) Frame is constant in time.
It acts as an extension of the parent Frame type so that an OffsetFrame<PhysicalFrame>, for example, can be treated as a PhysicalFrame. This enables Frames to be filtered by their type (e.g. Physical or not), regardless of whether or not the Frame is also an OffsetFrame. (A class whose super class is a template parameter is called a mixin class.)
OffsetFrames also have the property that if they form a chain or a tree, each OffsetFrame shares the same Base which is the parent of the first/root OffsetFrame in the tree. This allows Solvers and algorithms to work directly with the Base which can be more efficient.
OffsetFrame is an abstract class. Derive concrete subclasses in order to accommodate new Frame types that require their offsets to retain the same type as the parent. For example:
class PhysicalOffsetFrame : public OffsetFrame<PhysicalFrame>
See also
PhysicalOffsetFrame.
Template Parameters
C The type of the parent frame, as well as the super class. Must be of type Frame.
Author
Matt DeMers
Ajay Seth
Constructor & Destructor Documentation
template<class C > OpenSim::OffsetFrame< C >::OffsetFrame ()
By default, the frame is not connected to any parent frame, and its transform is an identity transform.
template<class C> OpenSim::OffsetFrame< C >::OffsetFrame (const C & parent, const SimTK::Transform & offset)
A convenience constructor that initializes the parent connection and offset Transform in the parent frame.
Parameters
[in] parent The parent reference frame.
[in] offset The offset transform between this frame and its parent
References OpenSim::OffsetFrame< C >::setOffsetTransform(), and OpenSim::OffsetFrame< C >::setParentFrame().
template<class C> OpenSim::OffsetFrame< C >::OffsetFrame (const std::string & name, const C & parent, const SimTK::Transform & offset)
A convenience constructor that initializes the parent connection by name and of the offset Transform in the parent frame.
Parameters
[in] name The name of this OffsetFrame.
[in] parent The parent reference frame.
[in] offset The offset Transform between this frame and its parent
template<class C> OpenSim::OffsetFrame< C >::OffsetFrame (const std::string & name, const std::string & parentName, const SimTK::Transform & offset)
A convenience constructor that initializes the parent connection by name and of the offset Transform in the parent frame.
Parameters
[in] name The name of this OffsetFrame.
[in] parentName The name of the parent reference Frame.
[in] offset The offset Transform between this frame and its parent
References OpenSim::OffsetFrame< C >::calcTransformInGround(), and OpenSim::OffsetFrame< C >::setOffsetTransform().
Member Function Documentation
template<class C > SimTK::SpatialVec OpenSim::OffsetFrame< C >::calcAccelerationInGround (const SimTK::State & state) const final override protected
References OpenSim::OffsetFrame< C >::getOffsetTransform(), and OpenSim::OffsetFrame< C >::getParentFrame().
Referenced by OpenSim::OffsetFrame< C >::calcVelocityInGround().
template<class C > SimTK::Transform OpenSim::OffsetFrame< C >::calcTransformInGround (const SimTK::State & state) const final override protected
References OpenSim::OffsetFrame< C >::calcVelocityInGround(), OpenSim::OffsetFrame< C >::getOffsetTransform(), and OpenSim::OffsetFrame< C >::getParentFrame().
Referenced by OpenSim::OffsetFrame< C >::OffsetFrame().
template<class C > SimTK::SpatialVec OpenSim::OffsetFrame< C >::calcVelocityInGround (const SimTK::State & state) const final override protected
References OpenSim::OffsetFrame< C >::calcAccelerationInGround(), OpenSim::OffsetFrame< C >::getOffsetTransform(), and OpenSim::OffsetFrame< C >::getParentFrame().
Referenced by OpenSim::OffsetFrame< C >::calcTransformInGround().
template<class C = Frame> OffsetFrame* OpenSim::OffsetFrame< C >::clone () const override pure virtual
Implemented in OpenSim::PhysicalOffsetFrame.
template<class C = Frame> void OpenSim::OffsetFrame< C >::connectSocket_parent (const Object & object) inline
Connect the 'parent' Socket to an object of type C.
Call finalizeConnections() afterwards to update the socket's connectee path property. The reference to the connectee set here takes precedence over the connectee path property.
Referenced by OpenSim::OffsetFrame< C >::setParentFrame().
template<class C > void OpenSim::OffsetFrame< C >::extendConnectToModel (Model & model) override protected
References OpenSim::OffsetFrame< C >::getConcreteClassName(), and OpenSim::OffsetFrame< C >::getParentFrame().
template<class C > void OpenSim::OffsetFrame< C >::extendFinalizeFromProperties () override protected
References OpenSim::OffsetFrame< C >::get_orientation(), and OpenSim::OffsetFrame< C >::get_translation().
template<class C > const Frame & OpenSim::OffsetFrame< C >::extendFindBaseFrame () const final override protected
Extend how OffsetFrame determines its base Frame.
References OpenSim::OffsetFrame< C >::getParentFrame().
template<class C > SimTK::Transform OpenSim::OffsetFrame< C >::extendFindTransformInBaseFrame () const final override protected
Extend how OffsetFrame determines its transform in its base Frame.
References OpenSim::OffsetFrame< C >::getOffsetTransform(), and OpenSim::OffsetFrame< C >::getParentFrame().
template<class C > void OpenSim::OffsetFrame< C >::extendScale (const SimTK::State & s, const ScaleSet & scaleSet) inline override
Scale the offset given scale factors for spatial (XYZ) dimensions.
References OpenSim::OffsetFrame< C >::get_translation(), OpenSim::OffsetFrame< C >::getParentFrame(), OpenSim::ModelComponent::InvalidScaleFactors, and OpenSim::OffsetFrame< C >::upd_translation().
Referenced by OpenSim::OffsetFrame< C >::setOffsetTransform().
template<class C = Frame> const SimTK::Vec3& OpenSim::OffsetFrame< C >::get_orientation () const inline
Get the value of the orientation property.
Referenced by OpenSim::OffsetFrame< C >::extendFinalizeFromProperties().
template<class C = Frame> const SimTK::Vec3& OpenSim::OffsetFrame< C >::get_translation () const inline
Get the value of the translation property.
Referenced by OpenSim::OffsetFrame< C >::extendFinalizeFromProperties(), and OpenSim::OffsetFrame< C >::extendScale().
template<class C = Frame> static const std::string& OpenSim::OffsetFrame< C >::getClassName () inline static
This returns "OffsetFrame_<T>_".
T is the template argument for this class. See getConcreteClassName() if you want the class name of the underlying concrete object instead.
template<class C = Frame> const std::string& OpenSim::OffsetFrame< C >::getConcreteClassName () const override pure virtual
Implemented in OpenSim::PhysicalOffsetFrame.
Referenced by OpenSim::OffsetFrame< C >::extendConnectToModel().
template<class C > const SimTK::Transform & OpenSim::OffsetFrame< C >::getOffsetTransform () const
Get the transform that describes the translational and rotational offset of this frame (F frame) relative to its parent frame (B frame).
This method returns the transform converting quantities expressed in F frame to quantities expressed in the B frame. This is mathematically stated as, vec_P = X_BF*vec_F , where X_BF is the transform returned by getTransform.
This transform is computed using the translation and orientation properties of this object.
Returns
offset The transform between this frame and its parent frame.
Referenced by OpenSim::OffsetFrame< C >::calcAccelerationInGround(), OpenSim::OffsetFrame< C >::calcTransformInGround(), OpenSim::OffsetFrame< C >::calcVelocityInGround(), and OpenSim::OffsetFrame< C >::extendFindTransformInBaseFrame().
template<class C > const C & OpenSim::OffsetFrame< C >::getParentFrame () const
Get the parent reference frame.
Referenced by OpenSim::OffsetFrame< C >::calcAccelerationInGround(), OpenSim::OffsetFrame< C >::calcTransformInGround(), OpenSim::OffsetFrame< C >::calcVelocityInGround(), OpenSim::OffsetFrame< C >::extendConnectToModel(), OpenSim::OffsetFrame< C >::extendFindBaseFrame(), OpenSim::OffsetFrame< C >::extendFindTransformInBaseFrame(), and OpenSim::OffsetFrame< C >::extendScale().
template<class C = Frame> static OffsetFrame* OpenSim::OffsetFrame< C >::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = OffsetFrame.safeDownCast(obj). This is equivalent to dynamic_cast<OffsetFrame*>(obj) in C++.
template<class C = Frame> void OpenSim::OffsetFrame< C >::set_orientation (const SimTK::Vec3 & value) inline
Set the value of the orientation property.
Referenced by OpenSim::OffsetFrame< C >::setOffsetTransform().
template<class C = Frame> void OpenSim::OffsetFrame< C >::set_translation (const SimTK::Vec3 & value) inline
Set the value of the translation property.
Referenced by OpenSim::OffsetFrame< C >::setOffsetTransform().
template<class C > void OpenSim::OffsetFrame< C >::setOffsetTransform (const SimTK::Transform & offset)
Sets the transform the translates and rotates this frame (F frame) from its parent frame (P frame).
You should provide the transform X_PF such that vec_P = X_PF*vec_F.
This transform is stored via the translation and orientation properties of this object.
Parameters
offset The transform between this frame and its parent frame.
References OpenSim::OffsetFrame< C >::extendScale(), OpenSim::OffsetFrame< C >::set_orientation(), and OpenSim::OffsetFrame< C >::set_translation().
Referenced by OpenSim::OffsetFrame< C >::OffsetFrame().
template<class C> void OpenSim::OffsetFrame< C >::setParentFrame (const C & parent)
Sets the parent reference frame.
References OpenSim::OffsetFrame< C >::connectSocket_parent().
Referenced by OpenSim::OffsetFrame< C >::OffsetFrame().
template<class C = Frame> SimTK::Vec3& OpenSim::OffsetFrame< C >::upd_orientation () inline
Get a writable reference to the orientation property.
template<class C = Frame> SimTK::Vec3& OpenSim::OffsetFrame< C >::upd_translation () inline
Get a writable reference to the translation property.
Referenced by OpenSim::OffsetFrame< C >::extendScale().
OpenSim Property, Socket, Output, Input Documentation
template<class C = Frame> SimTK::Vec3 OpenSim::OffsetFrame< C >::orientation
"Orientation offset (in radians) of this frame in its parent frame, " "expressed as a frame-fixed x-y-z rotation sequence."
This property appears in XML files under the tag <orientation>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_orientation(), upd_orientation(), set_orientation()
template<class C = Frame> C OpenSim::OffsetFrame< C >::parent
"The parent frame to this frame."
In an XML file, you can set this Socket's connectee path via the <socket_parent > element. This socket was generated with the OpenSim_DECLARE_SOCKET macro; see AbstractSocket for more information.
See also
connectSocket_parent()
template<class C = Frame> SimTK::Vec3 OpenSim::OffsetFrame< C >::translation
"Translational offset (in meters) of this frame's origin from the parent " "frame's origin, expressed in the parent frame."
This property appears in XML files under the tag <translation>. This property was generated with the OpenSim_DECLARE_PROPERTY macro; see Property to learn about the property system.
See also
get_translation(), upd_translation(), set_translation()
The documentation for this class was generated from the following file:
OpenSim/Simulation/Model/OffsetFrame.h