API: OpenSim::Output< T >::Channel Class Reference
OpenSim::Output< T >::Channel Class Reference
Public Member Functions
Channel ()=default
Channel (const Output< T > *output, const std::string &channelName)
const T & getValue (const SimTK::State &state) const
const Output< T > & getOutput () const
const std::string & getChannelName () const override
The name of this channel, or the name of the output that contains this Channel if it's in a single-value Output.
std::string getTypeName () const override
The name of the value type (e.g., double) produced by this channel.
std::string getName () const override
The name of this channel appended to the name of the output that contains this channel.
std::string getPathName () const override
This returns the absolute path name of the component to which this channel belongs prepended to the channel's name.
Public Member Functions inherited from OpenSim::AbstractChannel
virtual ~AbstractChannel ()=default
Constructor & Destructor Documentation
template<class T> OpenSim::Output< T >::Channel::Channel () default
template<class T> OpenSim::Output< T >::Channel::Channel (const Output< T > * output, const std::string & channelName) inline
Member Function Documentation
template<class T> const std::string& OpenSim::Output< T >::Channel::getChannelName () const inline override virtual
The name of this channel, or the name of the output that contains this Channel if it's in a single-value Output.
Implements OpenSim::AbstractChannel.
template<class T> std::string OpenSim::Output< T >::Channel::getName () const inline override virtual
The name of this channel appended to the name of the output that contains this channel.
The output name and channel name are separated by a colon (e.g., "markers:medial_knee"). If the output that contains this channel is a single-value Output, then this is just the Output's name.
Implements OpenSim::AbstractChannel.
template<class T> const Output<T>& OpenSim::Output< T >::Channel::getOutput () const inline
template<class T> std::string OpenSim::Output< T >::Channel::getPathName () const inline override virtual
This returns the absolute path name of the component to which this channel belongs prepended to the channel's name.
For example, this method might return something like "/model/metabolics|heat_rate:soleus_r".
Implements OpenSim::AbstractChannel.
References OpenSim::AbstractChannel::getName(), OpenSim::Output< T >::operator=(), and OpenSim::Output< T >::Output().
template<class T> std::string OpenSim::Output< T >::Channel::getTypeName () const inline override virtual
The name of the value type (e.g., double) produced by this channel.
Implements OpenSim::AbstractChannel.
template<class T> const T& OpenSim::Output< T >::Channel::getValue (const SimTK::State & state) const inline
The documentation for this class was generated from the following file:
OpenSim/Common/ComponentOutput.h