API: OpenSim::XMLDocument Class Reference
OpenSim::XMLDocument Class Reference
Public Member Functions
virtual ~XMLDocument ()
XMLDocument ()
XMLDocument (const std::string &aFileName)
XMLDocument (const XMLDocument &aDocument)
void copyDefaultObjects (const XMLDocument &aDocument)
void writeDefaultObjects (SimTK::Xml::Element &elmt)
const int & getDocumentVersion () const
SimTK::Xml::Element getRootDataElement ()
bool isEqualTo (XMLDocument &aOtherDocument, double toleranceForDoubles=1e-6, bool compareDefaults=false, bool compareVersionNumbers=false)
void setFileName (const std::string &aFileName)
const std::string & getFileName () const
void addDefaultObject (OpenSim::Object *aDefaultObject)
bool hasDefaultObjects () const
bool print (const std::string &aFileName=NULL)
Static Public Member Functions
static const int & getLatestVersion ()
static void renameChildNode (SimTK::Xml::Element &aNode, std::string oldElementName, std::string newElementName)
static void getVersionAsString (const int aVersion, std::string &aString)
static void addConnector (SimTK::Xml::Element &element, const std::string &connectorTag, const std::string &connectorName, const std::string &connectorValue)
This adds an XML element to element of the following form:
static void updateConnectors30508 (SimTK::Xml::Element &componentElt)
In version 30508, the XML syntax for Connectors changed: Previous:
static void addPhysicalOffsetFrame30505_30517 (SimTK::Xml::Element &element, const std::string &frameName, const std::string &parentFrameName, const SimTK::Vec3 &location, const SimTK::Vec3 &orientation)
static std::string updateConnecteePath30517 (const std::string &connecteeSetName, const std::string &connecteeName)
Convert component names into the appropriate paths based on where we know components were located in version 30000 model files.
static SimTK::Xml::Element findElementWithName (SimTK::Xml::Element &element, const std::string &name)
Find the first XML Element (depth-first search) with the provided name, anywhere in the XML document that contains element.
Constructor & Destructor Documentation
virtual OpenSim::XMLDocument::~XMLDocument () virtual
OpenSim::XMLDocument::XMLDocument ()
OpenSim::XMLDocument::XMLDocument (const std::string & aFileName)
OpenSim::XMLDocument::XMLDocument (const XMLDocument & aDocument)
Member Function Documentation
static void OpenSim::XMLDocument::addConnector (SimTK::Xml::Element & element, const std::string & connectorTag, const std::string & connectorName, const std::string & connectorValue) static
This adds an XML element to element of the following form:
<Connector_PhysicalFrame_ name="parent_frame">
    <connectee_name>...</connectee_name>
</Connector_PhysicalFrame_>
This syntax was revised in XML document version 30508; see updateConnectors30508(). As such, this function should not be used for updating versions 30508 or greater.
Referenced by OpenSim::TwoFrameLinker< C, F >::updateFromXMLNode().
void OpenSim::XMLDocument::addDefaultObject (OpenSim::Object * aDefaultObject)
static void OpenSim::XMLDocument::addPhysicalOffsetFrame30505_30517 (SimTK::Xml::Element & element, const std::string & frameName, const std::string & parentFrameName, const SimTK::Vec3 & location, const SimTK::Vec3 & orientation) static
Referenced by OpenSim::TwoFrameLinker< C, F >::updateFromXMLNode().
void OpenSim::XMLDocument::copyDefaultObjects (const XMLDocument & aDocument)
static SimTK::Xml::Element OpenSim::XMLDocument::findElementWithName (SimTK::Xml::Element & element, const std::string & name) static
Find the first XML Element (depth-first search) with the provided name, anywhere in the XML document that contains element.
If the XML document does not contain an element with name name, or if name is empty, then the returned Xml::Element is empty (Xml::Element::isValid() returns false).
const int& OpenSim::XMLDocument::getDocumentVersion () const inline
const std::string& OpenSim::XMLDocument::getFileName () const
static const int& OpenSim::XMLDocument::getLatestVersion () inline static
Referenced by OpenSim::Appearance::updateFromXMLNode(), and OpenSim::TwoFrameLinker< C, F >::updateFromXMLNode().
SimTK::Xml::Element OpenSim::XMLDocument::getRootDataElement ()
static void OpenSim::XMLDocument::getVersionAsString (const int aVersion, std::string & aString) static
bool OpenSim::XMLDocument::hasDefaultObjects () const inline
References OpenSim::Array< T >::getSize().
bool OpenSim::XMLDocument::isEqualTo (XMLDocument & aOtherDocument, double toleranceForDoubles = 1e-6, bool compareDefaults = false, bool compareVersionNumbers = false)
bool OpenSim::XMLDocument::print (const std::string & aFileName = NULL)
static void OpenSim::XMLDocument::renameChildNode (SimTK::Xml::Element & aNode, std::string oldElementName, std::string newElementName) static
void OpenSim::XMLDocument::setFileName (const std::string & aFileName)
static std::string OpenSim::XMLDocument::updateConnecteePath30517 (const std::string & connecteeSetName, const std::string & connecteeName) static
Convert component names into the appropriate paths based on where we know components were located in version 30000 model files.
Parameters
connecteeSetName "bodyset", "jointset", etc.
connecteeName The name of the connectee from the version 30000 file. Note: It is okay for connecteePath to be a reference to connecteeName.
Referenced by OpenSim::TwoFrameLinker< C, F >::updateFromXMLNode().
static void OpenSim::XMLDocument::updateConnectors30508 (SimTK::Xml::Element & componentElt) static
In version 30508, the XML syntax for Connectors changed: Previous:
<connectors>
    <Connector_PhysicalFrame_ name="parent_frame">
        <connectee_name>...</connectee_name>
    </Connector_PhysicalFrame_>
    <Connector_PhysicalFrame_ name="child_frame">
        <connectee_name>...</connectee_name>
    </Connector_PhysicalFrame_>
</connectors>
New:
<connector_parent_frame_connectee_name>...
    </connector_parent_frame_connectee_name>
<connector_child_frame_connectee_name>...
    </connector_child_frame_connectee_name>
If there is no <connectors> element, then this function does not edit componentElt.
void OpenSim::XMLDocument::writeDefaultObjects (SimTK::Xml::Element & elmt)
The documentation for this class was generated from the following file:
OpenSim/Common/XMLDocument.h