API: OpenSim::AbstractChannel Class Reference
OpenSim::AbstractChannel Class Reference abstract
One of the values of an Output.
Public Member Functions
virtual ~AbstractChannel ()=default
virtual const std::string & getChannelName () const =0
The name of this channel, or the name of the output that contains this Channel if it's in a single-value Output.
virtual std::string getTypeName () const =0
The name of the value type (e.g., double) produced by this channel.
virtual std::string getName () const =0
The name of this channel appended to the name of the output that contains this channel.
virtual std::string getPathName () const =0
This returns the absolute path name of the component to which this channel belongs prepended to the channel's name.
Detailed Description
One of the values of an Output.
Constructor & Destructor Documentation
virtual OpenSim::AbstractChannel::~AbstractChannel () virtual default
Member Function Documentation
virtual const std::string& OpenSim::AbstractChannel::getChannelName () const pure virtual
The name of this channel, or the name of the output that contains this Channel if it's in a single-value Output.
Implemented in OpenSim::Output< T >::Channel.
virtual std::string OpenSim::AbstractChannel::getName () const pure virtual
The name of this channel appended to the name of the output that contains this channel.
The output name and channel name are separated by a colon (e.g., "markers:medial_knee"). If the output that contains this channel is a single-value Output, then this is just the Output's name.
Implemented in OpenSim::Output< T >::Channel.
Referenced by OpenSim::Output< T >::getChannel(), and OpenSim::Output< T >::Channel::getPathName().
virtual std::string OpenSim::AbstractChannel::getPathName () const pure virtual
This returns the absolute path name of the component to which this channel belongs prepended to the channel's name.
For example, this method might return something like "/model/metabolics|heat_rate:soleus_r".
Implemented in OpenSim::Output< T >::Channel.
Referenced by OpenSim::AbstractOutput::getOwner().
virtual std::string OpenSim::AbstractChannel::getTypeName () const pure virtual
The name of the value type (e.g., double) produced by this channel.
Implemented in OpenSim::Output< T >::Channel.
Referenced by OpenSim::Output< T >::compatibleAssign(), and OpenSim::AbstractOutput::getOwner().
The documentation for this class was generated from the following file:
OpenSim/Common/ComponentOutput.h