API: OpenSim::ProbeReporter Class Reference
OpenSim::ProbeReporter Class Reference
A class for reporting the outputs of all model-connected Probes to file during a simulation.
Public Member Functions
ProbeReporter (Model *aModel=0)
ProbeReporter (const std::string &aFileName)
ProbeReporter (const ProbeReporter &aObject)
virtual ~ProbeReporter ()
ProbeReporter & operator= (const ProbeReporter &aActuation)
const Storage & getProbeStorage () const
Storage & updProbeStorage ()
void setModel (Model &aModel) override
set pointer to model to be analyzed.
int begin (const SimTK::State &s) override
int step (const SimTK::State &s, int setNumber) override
int end (const SimTK::State &s) override
void disableIntegrationOnlyProbes ()
int printResults (const std::string &aBaseName, const std::string &aDir="", double aDT=-1.0, const std::string &aExtension=".sto") override
Print the results of the analysis.
Public Member Functions inherited from OpenSim::Analysis
Analysis (Model *aModel=0)
Default constructor.
Analysis (const std::string &aFileName, bool aUpdateFromXMLNode=true)
Construct an object from file.
Analysis (const Analysis &aAnalysis)
Copy constructor.
virtual ~Analysis ()
Analysis & operator= (const Analysis &aAnalysis)
Assignment operator.
virtual void setStatesStore (const Storage &aStatesStore)
set states storage for analysis.
void setOn (bool aTrueFalse)
bool getOn () const
void setStartTime (double aStartTime)
double getStartTime () const
void setEndTime (double aEndTime)
double getEndTime () const
void setInDegrees (bool aTrueFalse)
Set whether or not to write the output of angles in degrees.
bool getInDegrees () const
virtual bool proceed (int aStep=0)
void setStepInterval (int aStepInterval)
int getStepInterval () const
void setColumnLabels (const Array< std::string > &aLabels)
Set the column labels for this analysis.
const Array< std::string > & getColumnLabels () const
void setStorageInterval (int aInterval)
int getStorageInterval () const
virtual ArrayPtrs< Storage > & getStorageList ()
void setPrintResultFiles (bool aToWrite)
bool getPrintResultFiles () const
Public Member Functions inherited from OpenSim::Object
virtual ~Object ()
Virtual destructor for cleanup.
bool isEqualTo (const Object &aObject) const
Equality operator wrapper for use from languages not supporting operator overloading.
Object & operator= (const Object &aObject)
Copy assignment copies he base class fields, including the properties.
virtual bool operator== (const Object &aObject) const
Determine if two objects are equal.
virtual bool operator< (const Object &aObject) const
Provide an ordering for objects so they can be put in sorted containers.
void setName (const std::string &name)
Set the name of the Object.
const std::string & getName () const
Get the name of this Object.
void setDescription (const std::string &description)
Set description, a one-liner summary.
const std::string & getDescription () const
Get description, a one-liner summary.
const std::string & getAuthors () const
Get Authors of this Object.
void setAuthors (const std::string &authors)
Set Authors of this object.
const std::string & getReferences () const
Get references or publications to cite if using this object.
void setReferences (const std::string &references)
Set references or publications to cite if using this object.
int getNumProperties () const
Determine how many properties are stored with this Object.
const AbstractProperty & getPropertyByIndex (int propertyIndex) const
Get a const reference to a property by its index number, returned as an AbstractProperty.
AbstractProperty & updPropertyByIndex (int propertyIndex)
Get a writable reference to a property by its index number, returned as an AbstractProperty.
bool hasProperty (const std::string &name) const
Return true if this Object has a property of any type with the given name, which must not be empty.
const AbstractProperty & getPropertyByName (const std::string &name) const
Get a const reference to a property by its name, returned as an AbstractProperty.
AbstractProperty & updPropertyByName (const std::string &name)
Get a writable reference to a property by its name, returned as an AbstractProperty.
template<class T >
bool hasProperty () const
Return true if this Object contains an unnamed, one-object property that contains objects of the given template type T.
template<class T >
const Property< T > & getProperty (const PropertyIndex &index) const
Get property of known type Property<T> as a const reference; the property must be present and have the right type.
template<class T >
Property< T > & updProperty (const PropertyIndex &index)
Get property of known type Property<T> as a writable reference; the property must be present and have the right type.
bool isObjectUpToDateWithProperties () const
Returns true if no property's value has changed since the last time setObjectIsUpToDateWithProperties() was called.
void readObjectFromXMLNodeOrFile (SimTK::Xml::Element &objectElement, int versionNumber)
We're given an XML element from which we are to populate this Object.
virtual void updateFromXMLNode (SimTK::Xml::Element &objectElement, int versionNumber)
Use this method to deserialize an object from a SimTK::Xml::Element.
void updateXMLNode (SimTK::Xml::Element &parent, const AbstractProperty *prop=nullptr) const
Serialize this object into the XML node that represents it.
bool getInlined () const
Inlined means an in-memory Object that is not associated with an XMLDocument.
void setInlined (bool aInlined, const std::string &aFileName="")
Mark this as inlined or not and optionally provide a file name to associate with the new XMLDocument for the non-inline case.
std::string getDocumentFileName () const
If there is a document associated with this object then return the file name maintained by the document.
int getDocumentFileVersion () const
If there is a document associated with this object then return its version number.
void setAllPropertiesUseDefault (bool aUseDefault)
bool print (const std::string &fileName) const
Write this Object into an XML file of the given name; conventionally the suffix to use is ".osim".
std::string dump () const
dump the XML representation of this Object into an std::string and return it.
virtual bool isA (const char *type) const
The default implementation returns true only if the supplied string is "Object"; each Object-derived class overrides this to match its own class name.
const std::string & toString () const
Wrapper to be used on Java side to display objects in tree; this returns just the object's name.
PropertySet & getPropertySet ()
OBSOLETE: Get a reference to the PropertySet maintained by the Object.
const PropertySet & getPropertySet () const
Auto-generated functions
static ProbeReporter * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "ProbeReporter".
ProbeReporter * clone () const override
Create a new heap-allocated copy of the concrete object to which this Object refers.
const std::string & getConcreteClassName () const override
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
Additional Inherited Members
Static Public Member Functions inherited from OpenSim::Analysis
static Analysis * safeDownCast (OpenSim::Object *obj)
For use in MATLAB and Python to access the concrete class.
static const std::string & getClassName ()
This returns "Analysis".
Static Public Member Functions inherited from OpenSim::Object
static void registerType (const Object &defaultObject)
Register an instance of a class; if the class is already registered it will be replaced.
static void renameType (const std::string &oldTypeName, const std::string &newTypeName)
Support versioning by associating the current Object type with an old name.
static const Object * getDefaultInstanceOfType (const std::string &concreteClassName)
Return a pointer to the default instance of the registered (concrete) Object whose class name is given, or NULL if the type is not registered.
template<class T >
static bool isObjectTypeDerivedFrom (const std::string &concreteClassName)
Return true if the given concrete object type represents a subclass of the template object type T, and thus could be referenced with a T*.
static Object * newInstanceOfType (const std::string &concreteClassName)
Create a new instance of the concrete Object type whose class name is given as concreteClassName.
static void getRegisteredTypenames (Array< std::string > &typeNames)
Retrieve all the typenames registered so far.
template<class T >
static void getRegisteredObjectsOfGivenType (ArrayPtrs< T > &rArray)
Return an array of pointers to the default instances of all registered (concrete) Object types that derive from a given Object-derived type that does not have to be concrete.
static bool PrintPropertyInfo (std::ostream &os, const std::string &classNameDotPropertyName, bool printFlagInfo=true)
Dump formatted property information to a given output stream, useful for creating a "help" facility for registered objects.
static bool PrintPropertyInfo (std::ostream &os, const std::string &className, const std::string &propertyName, bool printFlagInfo=true)
Same as the other signature but the class name and property name are provided as two separate strings.
static Object * makeObjectFromFile (const std::string &fileName)
Create an OpenSim object whose type is based on the tag at the root node of the XML file passed in.
static const std::string & getClassName ()
Return the name of this class as a string; i.e., "Object".
static void setSerializeAllDefaults (bool shouldSerializeDefaults)
Static function to control whether all registered objects and their properties are written to the defaults section of output files rather than only those values for which the default was explicitly overwritten when read in from an input file or set programmatically.
static bool getSerializeAllDefaults ()
Report the value of the "serialize all defaults" flag.
static bool isKindOf (const char *type)
Returns true if the passed-in string is "Object"; each Object-derived class defines a method of this name for its own class name.
static void setDebugLevel (int newLevel)
Set the debug level to get verbose output.
static int getDebugLevel ()
Get current setting of debug level.
static Object * SafeCopy (const Object *aObject)
Use the clone() method to duplicate the given object unless the pointer is null in which case null is returned.
static void RegisterType (const Object &defaultObject)
OBSOLETE alternate name for registerType().
static void RenameType (const std::string &oldName, const std::string &newName)
OBSOLETE alternate name for renameType().
Detailed Description
A class for reporting the outputs of all model-connected Probes to file during a simulation.
This analysis will, at each 'step_interval', cycle through all model Probes and retrieve the SimTK::Vector of probe outputs via getProbeOutputs(s) and store them into a Storage object, which will get recorded to a file at the termination of the simulation. The column labels for each Probe output will come from the overridden method Array<string> getProbeOutputLabels() from the specific Probe subclass. A schematic of the ProbeReporter functionality is shown below (diagram below assumes a single probe, but ProbeReporter will cycle through every Probe in the Model):
                              DEVELOPER NEEDS TO IMPLEMENT
                              THIS INSIDE THE CHILD PROBE
                              ============================
                              |  SimTK::Vector           |
                        |---> |  computeProbeOutputs(s)  | ----|
                        |     ============================     |
===================     |                                      |     ==========================
|  ProbeReporter  | -----                                      ----> |  Output to file        |
|  Analysis       | -----                                      ----> |  at end of simulation  |
===================     |                                      |     ==========================
                        |     ============================     |
                        |---> |  Array<string>           | ----|
                              |  getProbeOutputLabels()  |
                              ============================
                              DEVELOPER NEEDS TO IMPLEMENT
                              THIS INSIDE THE CHILD PROBE
Author
Tim Dorn
Constructor & Destructor Documentation
OpenSim::ProbeReporter::ProbeReporter (Model * aModel = 0)
OpenSim::ProbeReporter::ProbeReporter (const std::string & aFileName)
OpenSim::ProbeReporter::ProbeReporter (const ProbeReporter & aObject)
virtual OpenSim::ProbeReporter::~ProbeReporter () virtual
Member Function Documentation
int OpenSim::ProbeReporter::begin (const SimTK::State & s) override virtual
Reimplemented from OpenSim::Analysis.
ProbeReporter* OpenSim::ProbeReporter::clone () const inline override virtual
Create a new heap-allocated copy of the concrete object to which this Object refers.
It is up to the caller to delete the returned object when no longer needed. Every concrete object deriving from Object implements this pure virtual method automatically, via the declaration macro it invokes (e.g., OpenSim_DECLARE_CONCRETE_OBJECT()). Note that the concrete class overrides modify the return type to be a pointer to the concrete object; that still overrides the base class method because the return type is covariant with (that is, derives from) Object.
Implements OpenSim::Analysis.
void OpenSim::ProbeReporter::disableIntegrationOnlyProbes () inline
References OpenSim::Object::getName(), OpenSim::Probe::getOperation(), OpenSim::Set< T, C >::getSize(), and OpenSim::Probe::setEnabled().
int OpenSim::ProbeReporter::end (const SimTK::State & s) override virtual
Reimplemented from OpenSim::Analysis.
static const std::string& OpenSim::ProbeReporter::getClassName () inline static
This returns "ProbeReporter".
See getConcreteClassName() if you want the class name of the underlying concrete object instead.
const std::string& OpenSim::ProbeReporter::getConcreteClassName () const inline override virtual
Returns the class name of the concrete Object-derived class of the actual object referenced by this Object, as a string.
This is the string that is used as the tag for this concrete object in an XML file. Every concrete class derived from Object automatically overrides this method via the declaration macro it uses. See getClassName() to get the class name of the referencing (possibly abstract) class rather than the concrete object.
See also
getClassName()
Implements OpenSim::Analysis.
const Storage& OpenSim::ProbeReporter::getProbeStorage () const inline
ProbeReporter& OpenSim::ProbeReporter::operator= (const ProbeReporter & aActuation)
int OpenSim::ProbeReporter::printResults (const std::string & aBaseName, const std::string & aDir = "", double aDT = -1.0, const std::string & aExtension = ".sto") override virtual
Print the results of the analysis.
Parameters
aBaseName Base name of file to which to print the data.
aDir Directory name.
aDT Time interval between results (linear interpolation is used). If not supplied as an argument or negative, all time steps are printed without interpolation.
aExtension File extension if not the default ".sto".
Returns
-1 on error, 0 otherwise.
Reimplemented from OpenSim::Analysis.
virtual int OpenSim::ProbeReporter::record (const SimTK::State & s) protected virtual
static ProbeReporter* OpenSim::ProbeReporter::safeDownCast (OpenSim::Object * obj) inline static
For use in MATLAB and Python to access the concrete class.
Example: cObj = ProbeReporter.safeDownCast(obj). This is equivalent to dynamic_cast<ProbeReporter*>(obj) in C++.
void OpenSim::ProbeReporter::setModel (Model & aModel) override virtual
set pointer to model to be analyzed.
Parameters
aModel
Reimplemented from OpenSim::Analysis.
int OpenSim::ProbeReporter::step (const SimTK::State & s, int setNumber) override virtual
Reimplemented from OpenSim::Analysis.
Storage& OpenSim::ProbeReporter::updProbeStorage () inline
The documentation for this class was generated from the following file:
OpenSim/Analyses/ProbeReporter.h