API: OpenSim::Path Class Reference
OpenSim::Path Class Reference abstract
An abstract class for handling a Path.
Public Member Functions
Path (const char separator, const std::string invalidChars)
Create an empty path.
Path (const std::string path, const char separator, const std::string invalidChars)
Construct Path from a string, given separator character and a string of invalidChars.
Path (const std::vector< std::string > pathVec, const char separator, const std::string invalidChars, bool isAbsolute)
Construct Path from a vector of strings (pathVec), given separator character and a string of invalidChars.
Path (const Path &)=default
Use default copy constructor and assignment operator.
Path & operator= (const Path &)=default
virtual ~Path ()=default
Destructor.
std::string toString () const
Write out the path to a string with each element separated by the specified separator.
bool isAbsolute () const
Return true if this Path is an absolute path.
size_t getNumPathLevels () const
Return the number of levels (or elements) in the Path.
void pushBack (const std::string &pathElement)
Push a string to the back of a path (i.e.
virtual const char getSeparator () const =0
Pure virtual function that returns a char for the designated separator.
virtual const std::string getInvalidChars () const =0
Pure virtual function that returns a string of invalid characters.
bool isLegalPathElement (const std::string &pathElement) const
Return true if pathElement does not contain any chars from the list of getInvalidChars()
void trimDotAndDotDotElements ()
This removes "." elements and resolves ".." elements if possible (i.e., it will not remove leading ".." but otherwise will remove pairs of ".." and the preceding element).
Detailed Description
An abstract class for handling a Path.
A Path refers to a list of strings that represent a different level in a hierarchical structure. Each level is divided by designated separators (e.g., "/" or "\"). The string name related to each level is called a "pathElement" here. This class is unrelated to the GeometryPath class used in PathActuators.
Author
Carmichael Ong
Constructor & Destructor Documentation
OpenSim::Path::Path (const char separator, const std::string invalidChars)
Create an empty path.
OpenSim::Path::Path (const std::string path, const char separator, const std::string invalidChars)
Construct Path from a string, given separator character and a string of invalidChars.
This constructor removes "." elements and resolves ".." if possible.
OpenSim::Path::Path (const std::vector< std::string > pathVec, const char separator, const std::string invalidChars, bool isAbsolute)
Construct Path from a vector of strings (pathVec), given separator character and a string of invalidChars.
This constructor removes "." elements and resolves ".." if possible.
OpenSim::Path::Path (const Path &) default
Use default copy constructor and assignment operator.
virtual OpenSim::Path::~Path () virtual default
Destructor.
Member Function Documentation
std::vector<std::string> OpenSim::Path::formAbsolutePathVec (const Path & otherPath) const protected
Get an absolute path by resolving it relative to a given otherPath.
If the current Path is already absolute, return the same Path.
std::vector<std::string> OpenSim::Path::formRelativePathVec (const Path & otherPath) const protected
Find the relative Path between this Path and another Path (otherPath) (i.e.
the Path to go FROM otherPath TO this Path). Both Paths must be absolute.
virtual const std::string OpenSim::Path::getInvalidChars () const pure virtual
Pure virtual function that returns a string of invalid characters.
Implemented in OpenSim::ComponentPath.
size_t OpenSim::Path::getNumPathLevels () const inline
Return the number of levels (or elements) in the Path.
Referenced by OpenSim::Input< T >::finalizeConnection(), and OpenSim::Component::traversePathToComponent().
std::vector<std::string> OpenSim::Path::getParentPathVec () const inline protected
Return the sub-path that contains all pathElements except for the last one.
std::string OpenSim::Path::getPathElement (size_t pos) const inline protected
Return the pathElement from the specified position as a string.
This does not do any checks on the bounds.
std::string OpenSim::Path::getPathName () const inline protected
Return the last pathElement as a string.
virtual const char OpenSim::Path::getSeparator () const pure virtual
Pure virtual function that returns a char for the designated separator.
Implemented in OpenSim::ComponentPath.
bool OpenSim::Path::isAbsolute () const inline
Return true if this Path is an absolute path.
Referenced by OpenSim::Input< T >::finalizeConnection(), and OpenSim::Component::traversePathToComponent().
bool OpenSim::Path::isLegalPathElement (const std::string & pathElement) const
Return true if pathElement does not contain any chars from the list of getInvalidChars()
Referenced by OpenSim::AbstractSocket::checkConnecteePathProperty().
Path& OpenSim::Path::operator= (const Path &) default
void OpenSim::Path::pushBack (const std::string & pathElement) inline
Push a string to the back of a path (i.e.
the end). First checks if the pathElement is valid. This function does not alter whether this path is absolute or relative.
Referenced by OpenSim::Component::findComponent().
std::string OpenSim::Path::toString () const
Write out the path to a string with each element separated by the specified separator.
Referenced by OpenSim::Input< T >::finalizeConnection(), OpenSim::Socket< T >::findAndConnect(), OpenSim::Component::findComponent(), OpenSim::Component::getComponent(), OpenSim::ComponentPath::operator!=(), and OpenSim::ComponentPath::operator==().
void OpenSim::Path::trimDotAndDotDotElements ()
This removes "." elements and resolves ".." elements if possible (i.e., it will not remove leading ".." but otherwise will remove pairs of ".." and the preceding element).
This method also checks if a path is invalid due to an absolute path starting with "..".
Referenced by OpenSim::Component::traversePathToComponent().
The documentation for this class was generated from the following file:
OpenSim/Common/Path.h