API: OpenSim::ComponentPath Class Reference
OpenSim::ComponentPath Class Reference
A class for handling Paths for Components, deriving from Path.
Public Member Functions
ComponentPath ()
The default-constructed path is empty (an empty string).
ComponentPath (const std::string &path)
Construct a ComponentPath from a string.
ComponentPath (const std::vector< std::string > &pathVec, bool isAbsolute)
Constructor a ComponentPath from a vector that contains all subtree node names and a bool that indicates if the path is an absolute path.
bool operator== (const ComponentPath &other) const
bool operator!= (const ComponentPath &other) const
const char getSeparator () const override
Pure virtual function that returns a char for the designated separator.
const std::string getInvalidChars () const override
Pure virtual function that returns a string of invalid characters.
ComponentPath formAbsolutePath (const ComponentPath &otherPath) const
Get an absolute path by resolving it relative to a given otherPath.
ComponentPath formRelativePath (const ComponentPath &otherPath) const
Find the relative Path between this Path and another Path (otherPath) (i.e.
ComponentPath getParentPath () const
Return the sub-path that contains all subdirectory levels except for the last one.
std::string getParentPathString () const
Return the parent path as a string.
std::string getSubcomponentNameAtLevel (size_t index) const
Return a string of a subdirectory name at a specified level.
std::string getComponentName () const
Return a string of the name of the Component related to a ComponentPath.
Public Member Functions inherited from OpenSim::Path
Path (const char separator, const std::string invalidChars)
Create an empty path.
Path (const std::string path, const char separator, const std::string invalidChars)
Construct Path from a string, given separator character and a string of invalidChars.
Path (const std::vector< std::string > pathVec, const char separator, const std::string invalidChars, bool isAbsolute)
Construct Path from a vector of strings (pathVec), given separator character and a string of invalidChars.
Path (const Path &)=default
Use default copy constructor and assignment operator.
Path & operator= (const Path &)=default
virtual ~Path ()=default
Destructor.
std::string toString () const
Write out the path to a string with each element separated by the specified separator.
bool isAbsolute () const
Return true if this Path is an absolute path.
size_t getNumPathLevels () const
Return the number of levels (or elements) in the Path.
void pushBack (const std::string &pathElement)
Push a string to the back of a path (i.e.
bool isLegalPathElement (const std::string &pathElement) const
Return true if pathElement does not contain any chars from the list of getInvalidChars()
void trimDotAndDotDotElements ()
This removes "." elements and resolves ".." elements if possible (i.e., it will not remove leading ".." but otherwise will remove pairs of ".." and the preceding element).
Detailed Description
A class for handling Paths for Components, deriving from Path.
A ComponentPath uses a forward-slash ('/') as a separator always. It also specifies invalid characters in a Component name:
back-slash ('\')
forward-slash ('/')
asterisk ('*')
plus-sign ('+')
Author
Carmichael Ong
Constructor & Destructor Documentation
OpenSim::ComponentPath::ComponentPath ()
The default-constructed path is empty (an empty string).
OpenSim::ComponentPath::ComponentPath (const std::string & path)
Construct a ComponentPath from a string.
This will clean up the path, removing and resolving "." and ".." when possible.
OpenSim::ComponentPath::ComponentPath (const std::vector< std::string > & pathVec, bool isAbsolute)
Constructor a ComponentPath from a vector that contains all subtree node names and a bool that indicates if the path is an absolute path.
Member Function Documentation
ComponentPath OpenSim::ComponentPath::formAbsolutePath (const ComponentPath & otherPath) const
Get an absolute path by resolving it relative to a given otherPath.
If the current Path is already absolute, return the same Path.
ComponentPath OpenSim::ComponentPath::formRelativePath (const ComponentPath & otherPath) const
Find the relative Path between this Path and another Path (otherPath) (i.e.
the Path to go FROM otherPath TO this Path). Both Paths must be absolute.
std::string OpenSim::ComponentPath::getComponentName () const
Return a string of the name of the Component related to a ComponentPath.
This is just the last level of a ComponentPath.
Referenced by OpenSim::AbstractSocket::checkConnecteePathProperty(), and OpenSim::Component::findComponent().
const std::string OpenSim::ComponentPath::getInvalidChars () const inline override virtual
Pure virtual function that returns a string of invalid characters.
Implements OpenSim::Path.
ComponentPath OpenSim::ComponentPath::getParentPath () const
Return the sub-path that contains all subdirectory levels except for the last one.
std::string OpenSim::ComponentPath::getParentPathString () const
Return the parent path as a string.
const char OpenSim::ComponentPath::getSeparator () const inline override virtual
Pure virtual function that returns a char for the designated separator.
Implements OpenSim::Path.
std::string OpenSim::ComponentPath::getSubcomponentNameAtLevel (size_t index) const
Return a string of a subdirectory name at a specified level.
This is 0 indexed.
Referenced by OpenSim::Input< T >::finalizeConnection(), and OpenSim::Component::traversePathToComponent().
bool OpenSim::ComponentPath::operator!= (const ComponentPath & other) const inline
References OpenSim::Path::toString().
bool OpenSim::ComponentPath::operator== (const ComponentPath & other) const inline
References OpenSim::Path::toString().
The documentation for this class was generated from the following file:
OpenSim/Common/ComponentPath.h