API: OpenSim::FileAdapter Class Reference
OpenSim::FileAdapter Class Reference
FileAdapter is a DataAdapter that reads and writes files with methods read and writeFile respectively.
Public Member Functions
FileAdapter ()=default
FileAdapter (const FileAdapter &)=default
FileAdapter (FileAdapter &&)=default
FileAdapter & operator= (const FileAdapter &)=default
FileAdapter & operator= (FileAdapter &&)=default
virtual ~FileAdapter ()=default
Public Member Functions inherited from OpenSim::DataAdapter
virtual DataAdapter * clone () const =0
DataAdapter ()=default
DataAdapter (const DataAdapter &)=default
DataAdapter (DataAdapter &&)=default
DataAdapter & operator= (const DataAdapter &)=default
DataAdapter & operator= (DataAdapter &&)=default
virtual ~DataAdapter ()=default
DataAdapter::OutputTables read (const std::string &dataSourceSpecification) const
Public interface to read data from a dataSourceSpecification, typically a file or folder.
const std::shared_ptr< AbstractDataTable > getDataTable (const OutputTables &tables, const std::string tableName)
Generic interface to retrieve a specific table by name from read result.
Static Public Member Functions
static void writeFile (const InputTables &tables, const std::string &fileName)
Write a collection of tables to the given file.
static std::string findExtension (const std::string &filename)
Find the extension from a filename.
static std::vector< std::string > getNextLine (std::istream &stream, const std::string &delims)
Get the next line from the stream and tokenize/split the line using the given delimiters.
static std::vector< std::string > tokenize (const std::string &str, const std::string &delims)
Tokenize/split a given string using the given delimiters.
static std::shared_ptr< DataAdapter > createAdapterFromExtension (const std::string &fileName)
Create a concerte FileAdapter based on the extension of the passed in file and return it.
Static Public Member Functions inherited from OpenSim::DataAdapter
static bool registerDataAdapter (const std::string &identifier, const DataAdapter &adapter)
Register a concrete DataAdapter by its unique string identifier.
Detailed Description
FileAdapter is a DataAdapter that reads and writes files with methods read and writeFile respectively.
The read method is implemented in the base class and it calls the virtual extendRead method implemented by format specific subclasses. Typically you don't need to call read explicitly if reading one DataTable from file, instead use a constructor of the table from the specific file. e.g.
TimeSeriesTableVec3 table(filename);
Constructor & Destructor Documentation
OpenSim::FileAdapter::FileAdapter () default
OpenSim::FileAdapter::FileAdapter (const FileAdapter &) default
OpenSim::FileAdapter::FileAdapter (FileAdapter &&) default
virtual OpenSim::FileAdapter::~FileAdapter () virtual default
Member Function Documentation
static std::shared_ptr<DataAdapter> OpenSim::FileAdapter::createAdapterFromExtension (const std::string & fileName) static
Create a concerte FileAdapter based on the extension of the passed in file and return it.
This serves as a Factory of FileAdapters so clients don't need to know specific concrete subclasses, as long as the generic base class read interface is used
Referenced by OpenSim::DataTable_< double, SimTK::Rotation >::DataTable_(), and OpenSim::TimeSeriesTable_< SimTK::Vec3 >::TimeSeriesTable_().
static std::string OpenSim::FileAdapter::findExtension (const std::string & filename) static
Find the extension from a filename.
static std::vector<std::string> OpenSim::FileAdapter::getNextLine (std::istream & stream, const std::string & delims) static
Get the next line from the stream and tokenize/split the line using the given delimiters.
Referenced by OpenSim::DelimFileAdapter< T >::extendRead().
FileAdapter& OpenSim::FileAdapter::operator= (const FileAdapter &) default
FileAdapter& OpenSim::FileAdapter::operator= (FileAdapter &&) default
static std::vector<std::string> OpenSim::FileAdapter::tokenize (const std::string & str, const std::string & delims) static
Tokenize/split a given string using the given delimiters.
The delimiters are each required to be one character and the string is split if/when any of those characters are found. For example, a delimiter string " \t" specifies that either a space or a tab can act as the delimiter.
Referenced by OpenSim::DelimFileAdapter< T >::readElems().
static void OpenSim::FileAdapter::writeFile (const InputTables & tables, const std::string & fileName) static
Write a collection of tables to the given file.
Different file formats require different number/type of tables. See specific adapter's documentation to see what is required.
The documentation for this class was generated from the following file:
OpenSim/Common/FileAdapter.h