API: OpenSim::ComponentFilter Class Reference
OpenSim::ComponentFilter Class Reference abstract
A class to specify a filter to be used to iterate through components.
Public Member Functions
virtual ~ComponentFilter ()
Destructor of ComponentFilter, does nothing.
virtual bool isMatch (const Component &comp) const =0
This is the meat of the ComponentFilter, returns false if the passed in component should be skipped over.
virtual ComponentFilter * clone () const =0
clone() method needed to make a copy of the filter.
Detailed Description
A class to specify a filter to be used to iterate through components.
More flexible than filtering based on Type only. To write your custom filter, extend this class and implement the isMatch() and clone() methods.
Constructor & Destructor Documentation
OpenSim::ComponentFilter::ComponentFilter () inline protected
Default constructor of ComponentFilter, does nothing.
For use by derived classes only.
virtual OpenSim::ComponentFilter::~ComponentFilter () inline virtual
Destructor of ComponentFilter, does nothing.
References clone(), and isMatch().
Member Function Documentation
virtual ComponentFilter* OpenSim::ComponentFilter::clone () const pure virtual
clone() method needed to make a copy of the filter.
Implemented in OpenSim::ComponentFilterAbsolutePathNameContainsString, and OpenSim::ComponentFilterMatchAll.
Referenced by ~ComponentFilter().
virtual bool OpenSim::ComponentFilter::isMatch (const Component & comp) const pure virtual
This is the meat of the ComponentFilter, returns false if the passed in component should be skipped over.
Implemented in OpenSim::ComponentFilterAbsolutePathNameContainsString, and OpenSim::ComponentFilterMatchAll.
Referenced by OpenSim::ComponentFilterAbsolutePathNameContainsString::ComponentFilterAbsolutePathNameContainsString(), and ~ComponentFilter().
The documentation for this class was generated from the following file:
OpenSim/Common/ComponentList.h