API: OpenSim::DelimFileAdapter< T > Class Template Reference
OpenSim::DelimFileAdapter< T > Class Template Reference
DelimFileAdapter is a FileAdapter that reads and writes text files with given delimiters.
Public Member Functions
DelimFileAdapter ()=delete
DelimFileAdapter (const DelimFileAdapter &)=default
DelimFileAdapter (DelimFileAdapter &&)=default
DelimFileAdapter & operator= (const DelimFileAdapter &)=default
DelimFileAdapter & operator= (DelimFileAdapter &&)=default
~DelimFileAdapter ()=default
DelimFileAdapter (const std::string &delimitersRead, const std::string &delimterWrite)
Create the adapter by setting the delimiters.
DelimFileAdapter (const std::string &delimitersRead, const std::string &delimterWrite, const std::string &compDelimRead, const std::string &compDelimWrite)
Create the adapter by setting the delimiters.
DelimFileAdapter * clone () const override
Public Member Functions inherited from OpenSim::FileAdapter
FileAdapter ()=default
FileAdapter (const FileAdapter &)=default
FileAdapter (FileAdapter &&)=default
FileAdapter & operator= (const FileAdapter &)=default
FileAdapter & operator= (FileAdapter &&)=default
virtual ~FileAdapter ()=default
Public Member Functions inherited from OpenSim::DataAdapter
DataAdapter ()=default
DataAdapter (const DataAdapter &)=default
DataAdapter (DataAdapter &&)=default
DataAdapter & operator= (const DataAdapter &)=default
DataAdapter & operator= (DataAdapter &&)=default
virtual ~DataAdapter ()=default
DataAdapter::OutputTables read (const std::string &dataSourceSpecification) const
Public interface to read data from a dataSourceSpecification, typically a file or folder.
const std::shared_ptr< AbstractDataTable > getDataTable (const OutputTables &tables, const std::string tableName)
Generic interface to retrieve a specific table by name from read result.
Static Public Member Functions
static const std::string tableString ()
Key used for table associative array returned/accepted by write/read.
static std::string dataTypeName ()
Name of the data type T (template parameter).
Static Public Member Functions inherited from OpenSim::FileAdapter
static void writeFile (const InputTables &tables, const std::string &fileName)
Write a collection of tables to the given file.
static std::string findExtension (const std::string &filename)
Find the extension from a filename.
static std::vector< std::string > getNextLine (std::istream &stream, const std::string &delims)
Get the next line from the stream and tokenize/split the line using the given delimiters.
static std::vector< std::string > tokenize (const std::string &str, const std::string &delims)
Tokenize/split a given string using the given delimiters.
static std::shared_ptr< DataAdapter > createAdapterFromExtension (const std::string &fileName)
Create a concerte FileAdapter based on the extension of the passed in file and return it.
Static Public Member Functions inherited from OpenSim::DataAdapter
static bool registerDataAdapter (const std::string &identifier, const DataAdapter &adapter)
Register a concrete DataAdapter by its unique string identifier.
Detailed Description
template<typename T>
class OpenSim::DelimFileAdapter< T >
DelimFileAdapter is a FileAdapter that reads and writes text files with given delimiters.
CSVFileAdapter and MOTFileAdapter derive from this class and set the delimiters appropriately for the files they parse. The read/write functions return/accept a specific type of DataTable referred to as Table in this class. Header in the file is assumed to end with string "endheader" occupying a full line.
Constructor & Destructor Documentation
template<typename T> OpenSim::DelimFileAdapter< T >::DelimFileAdapter () delete
template<typename T> OpenSim::DelimFileAdapter< T >::DelimFileAdapter (const DelimFileAdapter< T > &) default
template<typename T> OpenSim::DelimFileAdapter< T >::DelimFileAdapter (DelimFileAdapter< T > &&) default
template<typename T> OpenSim::DelimFileAdapter< T >::~DelimFileAdapter () default
template<typename T > OpenSim::DelimFileAdapter< T >::DelimFileAdapter (const std::string & delimitersRead, const std::string & delimterWrite)
Create the adapter by setting the delimiters.
template<typename T > OpenSim::DelimFileAdapter< T >::DelimFileAdapter (const std::string & delimitersRead, const std::string & delimterWrite, const std::string & compDelimRead, const std::string & compDelimWrite)
Create the adapter by setting the delimiters.
Member Function Documentation
template<typename T > DelimFileAdapter< T > * OpenSim::DelimFileAdapter< T >::clone () const override virtual
Implements OpenSim::DataAdapter.
Reimplemented in OpenSim::STOFileAdapter_< T >.
template<typename T > std::string OpenSim::DelimFileAdapter< T >::dataTypeName () inline static
Name of the data type T (template parameter).
Referenced by OpenSim::DelimFileAdapter< T >::extendRead(), and OpenSim::DelimFileAdapter< T >::extendWrite().
template<typename T > DelimFileAdapter< T >::OutputTables OpenSim::DelimFileAdapter< T >::extendRead (const std::string & filename) const override protected virtual
Implementation of the read functionality.
Implements OpenSim::DataAdapter.
References OpenSim::DelimFileAdapter< T >::dataTypeName(), OpenSim::IO::eraseEmptyElements(), OpenSim::FileAdapter::getNextLine(), OpenSim::DelimFileAdapter< T >::readElems(), OpenSim::ValueArrayDictionary::setValueForKey(), and OpenSim::DelimFileAdapter< T >::tableString().
template<typename T > void OpenSim::DelimFileAdapter< T >::extendWrite (const InputTables & tables, const std::string & filename) const override protected virtual
Implementation of the write functionality.
Implements OpenSim::DataAdapter.
References OpenSim::DelimFileAdapter< T >::dataTypeName(), OpenSim::DelimFileAdapter< T >::tableString(), and OpenSim::DelimFileAdapter< T >::writeElem().
Referenced by OpenSim::STOFileAdapter_< T >::write().
template<typename T> DelimFileAdapter& OpenSim::DelimFileAdapter< T >::operator= (const DelimFileAdapter< T > &) default
template<typename T> DelimFileAdapter& OpenSim::DelimFileAdapter< T >::operator= (DelimFileAdapter< T > &&) default
template<typename T > SimTK::RowVector_< T > OpenSim::DelimFileAdapter< T >::readElems (const std::vector< std::string > & tokens) const inline protected
Read elements of type T (template parameter) from a sequence of tokens.
References OpenSim::FileAdapter::tokenize().
Referenced by OpenSim::DelimFileAdapter< T >::extendRead().
template<typename T > const std::string OpenSim::DelimFileAdapter< T >::tableString () static
Key used for table associative array returned/accepted by write/read.
Referenced by OpenSim::DelimFileAdapter< T >::extendRead(), and OpenSim::DelimFileAdapter< T >::extendWrite().
template<typename T> void OpenSim::DelimFileAdapter< T >::writeElem (std::ostream & stream, const T & elem, const unsigned & prec) const inline protected
Write an element of type T (template parameter) to stream with the specified precision.
Referenced by OpenSim::DelimFileAdapter< T >::extendWrite().
The documentation for this class was generated from the following file:
OpenSim/Common/DelimFileAdapter.h